

oracle:
  datasource:
    #jdbc:
    url: jdbc:oracle:thin:@10.132.71.41:1521:mktdb
    username: DBFACTURIER
    password: facturier
    driverClassName: oracle.jdbc.OracleDriver
    #jdbcUrl: 
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
spring:
  datasource:
    #jdbc:
    url: jdbc:postgresql://localhost:5432/batchdb
    username: postgres
    password: passer
    driverClassName: org.postgresql.Driver #org.hibernate.dialect.PostgreSQLDialect
    #jdbcUrl: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formatSql: true
# pour ne pas demarrer le job automatiquement
  batch:
    job:
      enabled: false
# creer les tables qu'utilise spring batch always never pour ne pas recreer
    initialize-schema: always
server:
  port: 8787

